9 Calendar Panel
S1robe/Pocket-Therapist pull request #106
Opened 2023-11-18 23:32 UTC by Cooljawty

# Description

A widget that shows a month long calendar with each day colored according to the strongest emotion entered that day. Selecting a day on the calendar will bring up a list of all entries made that day in an entres list page.

Fixes #9 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-27 02:38 UTC, S1robe commented on app/integration_test/calendar_test.dart
> +		}while(tester.widgetList(find.byKey(const Key("Navbar_Destination_Entries"))).isEmpty);
this is equivalent to await startApp.

Move the emotionList assignment to after this.

2023-11-27 02:58 UTC, S1robe reviewed
Please review these suggestions and comments, hope they help

2023-11-27 02:58 UTC, S1robe commented on app/integration_test/calendar_test.dart
> +		await tester.pump();
Tapping then pumping is better practice.

2023-11-27 02:58 UTC, S1robe commented on app/integration_test/calendar_test.dart
> +		await tester.pumpAndSettle();
remember the utilitiy method await tap(tster, finder)
Also remember to convert these to pump vs pumpAndSettle

2023-11-27 02:58 UTC, S1robe commented on app/lib/helper/dates_and_times.dart
> +  ({String day, String month, String weekday}) formatDate() {
Is this a tuple?

2023-11-27 02:58 UTC, S1robe commented on app/lib/pages/entries.dart
> +  }
What is the point of the target date?
Does that allow for it to be auto filtered? 
   If so we will need to allow a way omit it for default behavior?

2023-11-27 02:58 UTC, S1robe commented on app/lib/pages/entries.dart
> +	return testEntries;
if this is test data, it should go into a test file, not be here.
This will get bundled in to the real app, and there is no need to bloat the app.

2023-11-27 02:58 UTC, S1robe commented on app/lib/uiwidgets/calendar.dart
> +}
Similar answer to before, these look identical to theo nes that are already in entries.dart, If this is just test data it should be in a test file.

2023-12-01 03:40 UTC, Cooljawty commented
> Is it fine if the codecov/patch and codecov/project don't hit their targets?

Just added a couple tests to increase the coverage

2023-12-03 00:48 UTC, ian5924 approved these changes
I like the way the Calendar is designed, and how the colors are highlighted.
Goodjob!

2023-12-03 00:55 UTC, S1robe requested changes
Chagnes are still in progress, making this to ensure its not merged before branch is done.

2023-12-03 01:24 UTC, S1robe approved these changes
Approving, I will fix the code coverage.

2023-12-03 01:24 UTC, merged