10 new event button
S1robe/Pocket-Therapist pull request #107
Opened 2023-11-20 03:48 UTC by caelanot

# Description

Adds functionality for the plan button to create a JournalEntry with a completed field, that will eventually be able to be changed to mark plans that are completed. JournalEntries without a plan leave this blank.

Fixes #10 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Test for pressing the Plan button and checking corresponding dialogs show up

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2023-11-20 07:10 UTC, S1robe requested changes
Please review my comments. 
@caelanot This should issue should also include the plans panel, meaning the whole display section for plans should be included with this PR.

Please reach out to myself, @Cooljawty or @Benek6h if you need help with making these.

2023-11-20 07:10 UTC, S1robe commented on app/lib/pages/new_entry.dart
> +                                            : _selectedTags.remove(tag);
How does this stdSetState() work? I dont see many comments explaining what is going on here.

2023-11-20 07:10 UTC, S1robe commented on app/lib/pages/new_entry.dart
> +      plan: isPlan,
Why are we setting the creation date field to the date parameter, shouldnt there be a 'creationDate' and a 'scheduledDate' as part of the constructor.

2023-11-21 16:59 UTC, caelanot commented on app/lib/pages/entry.dart
>    }
Not something I changed, added in da4ff99.

2023-11-21 16:59 UTC, caelanot commented on app/lib/pages/new_entry.dart
> +                                            : _selectedTags.remove(tag);
<img width="822" alt="setState discussion" src="https://github.com/S1robe/Pocket-Therapist/assets/15092850/21c5c23e-fc32-4029-a876-6c697a3217ef">

2023-11-21 17:00 UTC, caelanot commented on app/lib/pages/new_entry.dart
> +      plan: isPlan,
Fixed, now sets up the creation date and the date picked for a plan.

2023-11-23 02:01 UTC, Cooljawty requested changes
I think this is a good implementation. Just one minor ui issue with the title for the entries page not changing

2023-11-23 08:13 UTC, caelanot commented on app/lib/pages/entries.dart
Fixed

2023-11-23 19:04 UTC, Cooljawty approved these changes
alright everything looks good!

2023-11-25 03:10 UTC, Benek6h commented on app/lib/pages/entries.dart
> -  //         ' by collaging some old book pages onto the page, creating a textured background. Then, I used watercolors to paint over the top,'
These need to be in here to showcase the app, when it is finished
They can be left commented out so they don't show up or break the tests, but they should not be deleted.

2023-11-25 03:11 UTC, Benek6h commented on app/lib/pages/entries.dart
> +                  widget.showPlans ? const Text("Plans") : const Text('Entries'),
Could you implement a little indication of when a plan is completed on the display card?

2023-11-25 03:16 UTC, Benek6h requested changes
This is great work, but there are a few things that I left comments on some parts that I belive need to be reviewed.
Also, could you please provide a media file?

2023-11-25 11:42 UTC, caelanot commented on app/lib/pages/entries.dart
> -  //         ' by collaging some old book pages onto the page, creating a textured background. Then, I used watercolors to paint over the top,'
Added the removed JournalEntries back in

2023-11-25 11:43 UTC, caelanot commented on app/lib/pages/entries.dart
> +                  widget.showPlans ? const Text("Plans") : const Text('Entries'),
Completed plans now show a orange squiggle through them when completed (design to be finalised and made bigger, but it shows)

2023-11-25 16:56 UTC, S1robe requested changes
Thank you for the hard work.
Please see my updated comments. 

If you need help let me know!

2023-11-25 16:56 UTC, S1robe commented on app/lib/pages/entries.dart
> +  const EntriesPage({super.key, this.showPlans = false});
What does this boolean do? It is not obvious to me.
It might show plans, but there is a whole separate page for this no?

2023-11-25 16:56 UTC, S1robe commented on app/lib/pages/entries.dart
At line 230, I cannot comment on it, but it is a map function that should really be a constant.
The 'displayOptions' is a const List<String>, so this really could be a const List<DropdownMenuItem>

2023-11-25 16:56 UTC, S1robe commented on app/lib/pages/entries.dart
>                                Text(() {
Please make a separate method for this child generation. 
It is hard to read and recognize that this is even a method call. (264-286)

2023-11-25 16:56 UTC, S1robe commented on app/lib/pages/entry.dart
> +  DateTime _displayDate = DateTime(1970, 12, 31);
These dont need to be private.

2023-11-25 16:56 UTC, S1robe commented on app/lib/pages/entry.dart
> +    status = planStatus;
Please convert the 'PlanStatus' to a bool?, this does not required an entire enum for this one function.

I initially suggested bool? because if its null we dont need to save it to the database with the rest of the entry.
There is more overhead of using an enum because its constant.

2023-11-25 16:56 UTC, S1robe commented on app/lib/pages/entry.dart
>    List<Emotion> getEmotions() => _emotions;
These dont need to be behind getters. Dart has no concept of this. 
https://dart.dev/tools/linter-rules/unnecessary_getters_setters

2023-11-25 16:56 UTC, S1robe commented on app/lib/pages/entry.dart
>    }
It does not matter if you didnt change it. it is apart of your commit, and related to your work. 
Plans have emotions and will still use this method to track them. 

Please see if you can modify this method to not need this catch all.

2023-11-25 16:56 UTC, S1robe commented on app/lib/pages/new_entry.dart
>                    padding: const EdgeInsets.all(20),
Please convert line 98-109 to a separate function, that returns a List<ActionChip> so that way the widget is easier to read.

2023-11-25 16:56 UTC, S1robe commented on app/lib/pages/new_entry.dart
> +                                            : _selectedTags.remove(tag);
I dont appreciate you sending our discord private messages. Regardless of what was said in a DM does not qualify any clarity to someone reading our code.

Remember that the point of comments is not for us, its for external parties or future maintainers to understand your work. 

Please explain what the point of stfSetState is or does in context.

2023-11-26 00:16 UTC, caelanot commented on app/lib/pages/entry.dart
>    List<Emotion> getEmotions() => _emotions;
Removed all getters besides Strongest Emotion

2023-11-26 00:17 UTC, caelanot commented on app/lib/pages/entry.dart
> +    status = planStatus;
planStatus is now a bool?

It's not for it being one function, it's to make it clearer what something means.

2023-11-26 01:50 UTC, S1robe approved these changes

2023-11-26 01:52 UTC, S1robe commented
Looks great, thanks for fixing the changes I requested.

2023-11-26 01:53 UTC, Benek6h approved these changes

2023-11-26 01:53 UTC, merged

2023-11-26 07:59 UTC, S1robe commented
Restored because the PR should be reverted to apply quality updates in favor of this one.