110 display loading screens while encrypting
S1robe/Pocket-Therapist pull request #114
Opened 2023-11-26 23:55 UTC by JikoJeans

# Description

This pull request seeks to add loading screens while the app is encrypting. This update also adds in isolates into the code base within the encryptor.dart file. Each Argon2.fromEncoded and hasher.converter has been wrapped with a thread.compute which triggers the app to calculate the hash on a secondary thread rather than freeze the main thread.

Fixes # 110

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I have added one new test case and provided the video below.
- [ ] Test A - the test case will test to make sure the animation is displayed.
- [ ] Test B - video below
https://github.com/S1robe/Pocket-Therapist/assets/143761091/3762cd78-bb5a-4b4a-947a-b6eb6ff6d5b8

**Test Configuration**:
* Firmware version: Android v14
* Hardware: Pixel 7
* Toolchain: Android API 34
* SDK: sdk_gphone64_x86_64

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Stuff Left to complete:
Merge

2023-11-28 04:46 UTC, S1robe requested changes
In provider/encryptor.dart

The encryption seems to take upward of a minute, and i am rather impatient, 
Chagne the iterations field from 9 to 6, the minimum recommended by OWASP (Offesntive Application Security) is 4. so 6 is still abvoe them.

This should speed things up a bit.

2023-11-28 04:46 UTC, S1robe commented on app/lib/provider/settings.dart
> +          ));
This seems to cause some jarring switching after creating a new password, there is a singular frame that something is on screen, I belive its Line 317

2023-11-28 06:44 UTC, S1robe reviewed
Looks great! I love this loading screen, maybe we can reduce some of the other parameters, or change the text on screen instead of loading... to generating keys...

2023-11-28 06:44 UTC, S1robe approved these changes

2023-11-28 15:30 UTC, JikoJeans commented on app/lib/provider/settings.dart
> +          ));
this has been updated to now only show the loading screen and after loading is done the user is taken to the second page.

2023-11-28 16:04 UTC, S1robe requested changes
thank you for reading into Isolates and the flutter foundations. 
Please review my comments. This also happened when I ran the app on my phone.
The text is messed up.

![image](https://github.com/S1robe/Pocket-Therapist/assets/78630000/4d294f98-bd1c-434a-9120-132f250fc109)

2023-11-28 17:55 UTC, JikoJeans commented on app/lib/provider/encryptor.dart
>  const int consumeMemory = 500000;
After updating the number of iterations in encryption from 9 to 6 the test for encryption sped up by a factor of 1/3 so the new timeout for the test has been updated from 6 to 4 minutes. I held off on adjusting any other values but for in the future I believe we should increase the value so long as it does not limit the apps compatibility with slower devices.

2023-11-28 17:59 UTC, JikoJeans commented
> thank you for reading into Isolates and the flutter foundations. Please review my comments. This also happened when I ran the app on my phone. The text is messed up.
> 
> ![image](https://private-user-images.githubusercontent.com/78630000/286321521-4d294f98-bd1c-434a-9120-132f250fc109.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTQwNjgsIm5iZiI6MTcwMTE5Mzc2OCwicGF0aCI6Ii83ODYzMDAwMC8yODYzMjE1MjEtNGQyOTRmOTgtYmQxYy00MzRhLTkxMjAtMTMyZjI1MGZjMTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE3NDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZDExNTc4YjY4OTM3YTE4OTIwNjE5Yjc2ZjE1MjdlN2RjZWQ4YTczODViNTgyODUzYjUwZDk5MzcyY2Y1ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3rZPTUW7TGo_fsSGmUq7oWE6GSwPbJp1wMhA-Z6V-YI)

![Capture](https://github.com/S1robe/Pocket-Therapist/assets/143761091/e78d4a2e-d3a7-4eaa-8ae6-baf150f6dde3)
I have adjusted the layout of the widgets within the animation widget so now the test should not overflow during either loading screen.

2023-11-28 18:40 UTC, Benek6h commented on app/lib/uiwidgets/decorations.dart
> +  final loadingImage = Image.asset(
Could we use the glasses png rather than the logo?

2023-11-28 18:48 UTC, Benek6h requested changes
This looks amazing!
Thank you Miguel for getting this to work and doing the proper research.

I did notice a few issues and left comments about them, but they should be quick fixes!

2023-11-28 20:49 UTC, JikoJeans commented on app/lib/uiwidgets/decorations.dart
> +  final loadingImage = Image.asset(
copy that in the latest update we are using the glasses.png, I had to modify one of the existing glasses.png to center it and I named it centered glasses frame.

2023-11-28 20:51 UTC, JikoJeans commented on app/lib/provider/settings.dart
> +      builder: (context) => AlertDialog(
Nice catch, I have been staring at the loading screen the longest and I had yet to notice the issues going on in the background thank you for spotting it! I have updated the barriers so that only the first barrier is visible and I toned down visibility to help fix the color issue.
![Capture2](https://github.com/S1robe/Pocket-Therapist/assets/143761091/8538a7db-a723-441a-b4fb-0c3456622564)
![Capture1](https://github.com/S1robe/Pocket-Therapist/assets/143761091/02ee4e9e-fbb7-4bca-8752-1426ed8ffb9d)
![Capture](https://github.com/S1robe/Pocket-Therapist/assets/143761091/de4f1f51-fdf2-4c6d-95b8-7edd280b3264)

2023-11-29 00:10 UTC, S1robe approved these changes

2023-11-29 00:14 UTC, Benek6h approved these changes
Awesome! Thanks for implementing the changes I requested super quickly!
Great work Miguel!

2023-11-29 00:16 UTC, merged