115 plans re implementation
S1robe/Pocket-Therapist pull request #116
Opened 2023-11-28 08:02 UTC by caelanot

# Description

Re-implements the plans feature to show plans and mark them as complete. Plans are shown on the entries page as well, but only non-plans or plans are shown.

Fixes #115 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test creating new plan, and make sure it only appears on plan page

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2023-11-28 15:13 UTC, S1robe commented on app/integration_test/entries_test.dart
This is entirely formatting?

2023-11-28 15:39 UTC, S1robe requested changes
Thank you for your hard work, there is still much to be done though.
Please review my comments and let me know if you have any trouble or think ive misinterpreted. 

Reach out if you need something :smile_cat:

2023-11-28 15:39 UTC, S1robe commented on app/lib/pages/entries.dart
>      return Consumer<ThemeSettings>(
Why is there not a separate lite for plans like we discussed? Did you find a better way to do it?
If we maintain a separate list of plans then we not only dont need any of this, but we also keep track of plans separately. They are saved together and filtered back out after loading. 

Im not sure how this is better though. Could you explain or change it?

2023-11-28 15:39 UTC, S1robe commented on app/lib/pages/entries.dart
> +                          // if changed set new display option
Could you make this a const List<DropdownMenuItem<String>> 
There is no reason to rebuild this every time the widget is displayed,
The source 'displayOptions' is const and will never change, so this list will never change.

2023-11-28 15:39 UTC, S1robe commented on app/lib/pages/entries.dart
> +                              ],
Please convert the whole thing to a function, have the method parseRange return a List<AppropriateWidgetClassHere>

Additionally, its standard practice to place methods before their invocation. Please move it to above the build method.
Thank you.

2023-11-28 15:39 UTC, S1robe commented on app/lib/pages/entries.dart
> +    }());
Like mentioned above pleease make this turn into a list, and remove the anonmous function.

You can do that simply by copying from the '() { '  to the last }, then placing this at the end of the method name, and updating the parameters to the method, and of course fixing any other errors along the way.

2023-11-28 15:39 UTC, S1robe commented on app/lib/provider/entry.dart
>    }) {
Shouldnt there be a completedDate and scheduledDate paramters?
If these are plans, i know that I would like to have those kinds of variables.
Especially for the future plan of reminders.

2023-11-28 15:39 UTC, S1robe commented on app/lib/uiwidgets/decorations.dart
> +            : onDestinationSelected!(index);
Instead of if () if()
try if ( cond1 && cond2 )

2023-11-28 15:39 UTC, S1robe commented on app/lib/uiwidgets/decorations.dart
> -        selectedIndex = index;
This line is necessary and should be returned, otherwise it will enable users to repeatedly visit pages that they are already on.

2023-11-28 15:39 UTC, S1robe commented on app/lib/uiwidgets/decorations.dart
>            setState(() {});
This rebuilds the widget anytime its tapped, it has nothing to do with changes.

2023-11-28 15:39 UTC, S1robe commented on app/lib/uiwidgets/decorations.dart
> +                                        ),
Love this! maybe use the accentColor from settings as the decoration color?

2023-11-28 15:39 UTC, S1robe commented on app/lib/uiwidgets/decorations.dart
>                    const Spacer(),
This may be a fix for now, but im not sure if this is the best way. I think this may cause an issue for rotating the phone or on smaller devices

Ideally you would put all of this in a Row and use 'spaceEvenly'

2023-11-28 15:39 UTC, S1robe commented on app/lib/uiwidgets/decorations.dart
> +                          })),
1. Why do we need a container here at all if this isnt plan as elluded by planCompleted being null.
2. There is an anonymous method again for on Pressed. Please convert it to a named method above the current build method.

2023-11-28 15:47 UTC, S1robe commented
Thank you again for the hard work, I have one more thing that needs to be changed. 
This value should be scaled to only display 0-60. 
This affects both Plans and Entries. Could you fix it in this PR?

![image](https://github.com/S1robe/Pocket-Therapist/assets/78630000/b7139f11-514a-444b-b511-d5a4f6ca03f8)

2023-11-28 16:22 UTC, S1robe commented on app/lib/uiwidgets/decorations.dart
> -        selectedIndex = index;
Discussed externally, it works without this line. Better than before.

Thanks!

2023-11-28 19:28 UTC, caelanot commented on app/lib/uiwidgets/decorations.dart
>                    const Spacer(),
Getting rid of the Spacer causes the elements to shift around and not be neatly aligned between the pages, leaving it in for now.

2023-11-28 19:47 UTC, caelanot commented on app/lib/uiwidgets/decorations.dart
> +                          })),
Container removed, leaving the anonymous method because it is only being called in this one spot. Adding a named method for this single operation would make it harder to read.

2023-11-28 19:47 UTC, caelanot commented on app/lib/pages/entries.dart
>      return Consumer<ThemeSettings>(
Fixed, added plans list to keep the two separate.

2023-11-28 19:59 UTC, caelanot commented on app/lib/pages/entries.dart
> +                              ],
Doing this doesn't seem reasonable to return a list, because it's being added to the children array and would likely obscure reading the code. `parseRange` has been modified to return a string so it can instead append `Text(getTimeRange(time))` to the list, which hopefully makes things clearer.

2023-11-28 20:01 UTC, caelanot commented on app/lib/uiwidgets/decorations.dart
> +                                        ),
Fixed, now uses the primary theme color for the strikethrough.

2023-11-28 20:02 UTC, caelanot commented on app/lib/uiwidgets/decorations.dart
>            setState(() {});
Changed the comment to be more clear

2023-11-28 20:24 UTC, S1robe commented on app/lib/uiwidgets/decorations.dart
> +                          })),
What if the user wanted to multi toggle them
Then we would need to add it in as a function? 

It doesnt make it harder to read by naming the function clearly. 

Please move it to a function above the build method.

2023-11-28 23:20 UTC, S1robe commented on app/lib/provider/entry.dart
>    }) {
This actually does matter, its future proofing for reminders.

Once we add those, it will be needed. Plans should maintain their creation date, and have scheduled date so we can also report a stat for completion rate.

2023-11-29 01:31 UTC, S1robe approved these changes
Awesome job, thank you for getting this done so quickly.
Thank you for creating the child class Plans I think that this will be easier to implement with.

2023-11-29 01:58 UTC, Benek6h approved these changes
Awesome work! Thank you for getting this done so quickly . With the way it is set up right now, it will be much easier to manage plans.

2023-11-29 01:59 UTC, merged

2023-12-03 18:20 UTC, S1robe commented
This needed to be reimplemented again, see #120