29 display card
S1robe/Pocket-Therapist pull request #60
Opened 2023-10-17 01:51 UTC by Cooljawty

# Description

Adds the DisplayCard widget which will be used to display a journal entry. Redirects to full entry when tapped

Fixes #29

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test the DisplayCard constructor. The build method has all the necessary attributes so builds fine
- [x] Ensure all content is displayed. Checks to make sure that 3 entries are displayed and searches for them by title and body.
- [x] Test tapping on display card so that entry title and full text is opened in a new page

**Test Configuration**:
* Firmware version: Android 14
* Hardware: Google Pixel 3a (emulated)
* Toolchain: Android API 32
* SDK: sdk_gphone6_65

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-10-17 05:06 UTC, S1robe commented on app/lib/pages/entries.dart
> +							const DisplayCard(content: [
I think that we could change this up, to be more encapsulated. 
Should we really be putting the content direct into the display card?

2023-10-17 05:20 UTC, S1robe requested changes
Please review my suggestions, I think that DataCard could handle gestures and display an overlay that will display the content. Maybe using the RichText style would look good?

2023-10-17 05:20 UTC, S1robe commented on app/lib/uiwidgets/cards.dart
> +	final List<Map<String,String>> content;
Shouldn't display cards have one entry per card?
Additionally, should we have them as Map<String, String> or is that even necessary.

What if we had parameters that mirrored that of our journal entries.

2023-10-17 05:20 UTC, S1robe commented on app/lib/uiwidgets/cards.dart
> +		return Flexible(
What if the datacard listened for gestures and was able to handle them by opening the content in a convenient overlay?

2023-10-17 05:20 UTC, S1robe commented on app/test/display_card_test.dart
> +import 'package:flutter_test/flutter_test.dart';
These test cases look good for what was provided but will need to be updated in accordance with the other requested changes.

2023-10-17 19:44 UTC, Cooljawty commented on app/lib/uiwidgets/cards.dart
> +	final List<Map<String,String>> content;
From the description in the DD the display card displays multiple entries/events.
Also I decided to use a map since it's supposed to support entries and events. If we just want to pass entries then I'll also have to implement the Journal Entry class

2023-10-17 21:14 UTC, S1robe commented on app/lib/uiwidgets/cards.dart
> +	final List<Map<String,String>> content;
Fair, but you dont need to implement the whole class, it will be a dictionary. What i was looking for was one dictionary per DisplayCard. 

Because in the DD its 1 entry per card.
Thanks.

2023-10-18 01:45 UTC, Cooljawty commented on app/lib/uiwidgets/cards.dart
> +		return Flexible(
In this case I think tapping the display card would expand it. Then the back gesture would shrink it and the navigation bar will have a button to edit the entry.

2023-10-18 01:45 UTC, Cooljawty commented on app/lib/uiwidgets/cards.dart
> +		return Flexible(
And expanding would show the full entryText

2023-10-18 17:49 UTC, S1robe requested changes
DisplayCard ideally will respond to input and then display the content in an overlay like mentioned before. 

Doing it like this is like the front end, then when the database is completed and can be read from, all we have to do is dump the data into the constructor, and tweak the display later.

Please let me know if you have any issues with implementing this, or think there is a better way.

2023-10-18 17:49 UTC, S1robe commented on app/lib/uiwidgets/cards.dart
> +class _DisplayCardState extends State<DisplayCard> {
We might want to have this be able to respond to gestures. Check out GestureDetector.

2023-10-18 17:49 UTC, S1robe commented on app/test/display_card_test.dart
> +import 'package:flutter_test/flutter_test.dart';
Missing gesture detection

2023-10-21 20:24 UTC, Cooljawty reviewed
All comments have been addressed, and all test cases are passing

2023-10-22 02:25 UTC, S1robe submitted a review, later dismissed
Good job with addressing the previous requests. There are some things missing from the previous suggestions, I think there could be more formatting and structure included in Entry overlay, pay attention to the names of your classes as well. 

Thank you for your contribution.

2023-10-22 02:25 UTC, S1robe commented on app/lib/pages/entry.dart
> +class EntryPage<T> extends StatefulWidget {
Why is this parametrized, if it's only supposed to work with Entries from entry.dart?

2023-10-22 02:25 UTC, S1robe commented on app/lib/pages/entry.dart
> +  const EntryPage({super.key, required this.entry});
Maybe EntryPage should just be called Entry? This could be misleading since we now have two of the exact same classes.

2023-10-22 02:25 UTC, S1robe commented on app/lib/pages/entries.dart
>                ElevatedButton(onPressed: (){
Is this formatting indented heavily? On my screen it seems to be, can we make it condensed?

2023-10-22 02:25 UTC, S1robe commented on app/lib/pages/entry.dart
> +								Navigator.of(context).pushReplacement(EntriesPage.route());
This is just a new page on top of the other one, shouldn't there be more structure to the overlay for a journal entry? More than just putting the test on screen in a column arrangement?

2023-10-22 02:34 UTC, S1robe commented
Additionally, please ensure you download the updated codecov.yml file and place it in the root of your directory, it is the reason why the checks are showing up as failing when the tests are passing.

Thank you.

2023-10-22 17:55 UTC, Cooljawty commented on app/lib/pages/entry.dart
> +								Navigator.of(context).pushReplacement(EntriesPage.route());
I think the entry page should be it's own pull request. Since it will need to be formatted, have test cases, and I image it will have to tie in to entry editing.

2023-10-22 17:59 UTC, Cooljawty commented
> Additionally, please ensure you download the updated codecov.yml file and place it in the root of your directory, it is the reason why the checks are showing up as failing when the tests are passing.
> 
> Thank you.

I've compared the yml file with the most updated on in main, and they are the same.

2023-10-25 03:33 UTC, Benek6h commented on app/lib/pages/entry.dart
> +								Navigator.of(context).pushReplacement(EntriesPage.route());
Yes, but that would cause them to have to recode your code. Your code should be future-proofed and structured.

2023-10-25 03:39 UTC, Benek6h submitted a review, later dismissed
Please fix how you display the widgets. The way that we have it now is hardcoded and it would be a pain to have journal entries displayed this way. 

Take a look at this flutter doc that may help!
https://docs.flutter.dev/cookbook/lists/mixed-list

2023-11-01 03:19 UTC, S1robe requested changes
Please look over my comments, Thank you for your contribution.

2023-11-01 03:19 UTC, S1robe commented on app/lib/pages/entries.dart
> +
Great!

2023-11-01 03:19 UTC, S1robe commented on app/lib/uiwidgets/cards.dart
> +	Route<dynamic>? pageRoute;
Why would a Display card have a page route?

2023-11-01 03:19 UTC, S1robe commented on app/lib/pages/entry.dart
> +			),
Can you fix this formatting?

2023-11-01 03:19 UTC, S1robe commented on app/test/display_card_test.dart
> +	});
Can you fix this as well?

2023-11-01 03:19 UTC, S1robe commented on app/test/display_card_test.dart
> +	});
All of these have the same coverage? Comments might help me here.

2023-11-01 03:19 UTC, S1robe commented on app/test/display_card_test.dart
> +	});
This one looks like it should cover everything.

2023-11-01 03:19 UTC, S1robe commented on app/test/display_card_test.dart
> +}
What does this do, dont we have a class that does this? Isnt this supposed to be testing the actual class not this one?

2023-11-01 19:01 UTC, Cooljawty commented on app/lib/pages/entry.dart
> +			),
Its because github displays tabs with 8 spaces instead of 2

2023-11-01 19:02 UTC, Cooljawty commented on app/test/display_card_test.dart
> +	});
Its because github displays tabs with 8 spaces instead of 2

2023-11-01 19:04 UTC, Cooljawty commented on app/test/display_card_test.dart
> +	});
I split each into seperate tests to help narrow down errors. Having the whole display card covered under one test means that it could fail at multiple points, but narrowing down the source of the issue would be made harder as it just displays the one test.

2023-11-01 19:05 UTC, Cooljawty commented on app/test/display_card_test.dart
> +}
This is to test just the DisplayOnCard Mixin. since its more generic having a test object mean We can test issues specific to the mixin, and not with the specific implementation of the mixin.

2023-11-01 19:46 UTC, S1robe commented on app/test/display_card_test.dart
> +	);
What is the point of this object, its not in production code?

2023-11-01 19:47 UTC, S1robe commented on app/test/display_card_test.dart
> +	});
Im not sure what that means, the rest of the document is fine.... when I download it, it looks the same

2023-11-01 20:07 UTC, Cooljawty commented on app/test/display_card_test.dart
> +	});
Whats your tabstop set to?

2023-11-03 04:58 UTC, caelanot commented
Looks good, though I'd agree to change your tabs into spaces instead of hard tabs, as it makes the code harder to read.

2023-11-05 00:29 UTC, S1robe approved these changes
Looks great, thanks for being so dedicated to this.

2023-11-05 05:46 UTC, caelanot approved these changes
I've used most of these already within #80 , merging just those might be a little annoying but all the code looks good.

2023-11-05 19:02 UTC, merged