19 open existing vault button
S1robe/Pocket-Therapist pull request #65
Opened 2023-10-18 20:46 UTC by caelanot

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] openDatabaseFile: Test trying to read a file from a filepath
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain: android API 34
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-22 07:37 UTC, caelanot commented
Opening for review now - 
Patrol has been unsupportive yet for testing the file picker, but they work on device. This leaves the file manager at partially untested, mainly those that involve opening the file picker.

2023-10-22 21:46 UTC, Cooljawty commented on app/lib/pages/settings.dart
> +                )
There's a merge conflict with the new settings page. You should be able to move this to the right button.

2023-10-22 23:03 UTC, caelanot commented on app/lib/pages/settings.dart
> +                )
Modified the settings page to add the button following the same style as the others, this should now be resolved.

2023-10-23 21:27 UTC, S1robe requested changes
Thank you for your contribution. Great work, please see my requested changes and increase code coverage to 90%+. If you need anything, please reach out.

2023-10-23 21:27 UTC, S1robe commented on app/test/file_manager_test.dart
> +    openDatabaseFile(filename);
This needs to be 'awaited on', or it will fail.

2023-10-23 21:27 UTC, S1robe commented on app/test/file_manager_test.dart
> +    const filename = "file.txt";
Please add a comment that indcates where this file is created to. I am not sure where it will end up, so im not sure that it correctly opens it afterward.

2023-10-25 03:41 UTC, Benek6h commented
Could you add a media file, video or picture?

2023-10-25 21:56 UTC, caelanot commented on app/test/file_manager_test.dart
> +    const filename = "file.txt";
File now no longer is created on hard drive when testing.

2023-10-25 21:58 UTC, caelanot commented on app/test/file_manager_test.dart
> +    openDatabaseFile(filename);
File contents are awaited on when reading.

2023-10-26 04:20 UTC, S1robe approved these changes
Looks good, thanks for updating your commit.

2023-10-27 16:33 UTC, Benek6h approved these changes
This looks good to me. Great job, Caelan!

2023-10-28 21:14 UTC, merged