7 Navigation Bar
S1robe/Pocket-Therapist pull request #68
Opened 2023-10-21 21:24 UTC by Cooljawty

# Description

Provides a widget for navigating thrugh to different pages in the app

Fixes #7 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] Test NavBar Constructor

**Test Configuration**:

* Firmware version: Android 14
* Hardware: Google Pixel 3a (emulated)
* Toolchain: Android API 32
* SDK: sdk_gphone6_65

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-23 21:05 UTC, S1robe commented
Please include a short video or pictures of what your changed version looks like, I am not sure what this will look like.

Thank you,

2023-10-23 21:19 UTC, Cooljawty commented
> Please include a short video or pictures of what your changed version looks like, I am not sure what this will look like.
> 
> Thank you,

I attached a video in the demonstration section. Guess it's now showing a preview

2023-10-23 21:31 UTC, S1robe commented
I see, thank you. Sorry, my mistake. This looks really good!

Can you see about making it persist between pages, where the buttons on the navbar change with the page that it is being displayed over?

Please let me know if you need anything else!

2023-10-25 15:00 UTC, S1robe requested changes
Thank you for your contributions.
Can you make it persist across the different pages that we already have?

2023-11-01 21:28 UTC, caelanot commented
Enum/Boolean for push type (only some pages should have the back button go to previous page, settings for example)

2023-11-02 03:08 UTC, Benek6h requested changes
Please look over my comments. Good job with the test cases!

2023-11-02 03:08 UTC, Benek6h commented on app/lib/provider/theme_settings.dart
> +			),
Why would this need to be in the app's theme settings? They don't change across the light and dark themes, so this shouldn't be in the theme settings. It should be in the nav bars initial build.

2023-11-02 03:08 UTC, Benek6h commented on app/lib/uiwidgets/navbar.dart
> +			destinations: destinations.map((destination) => destination.toWidget()).toList(),
Navbar theme should be here

2023-11-04 22:39 UTC, Benek6h reviewed
Please refer to my comment about your navbar_test.dart file

2023-11-04 22:45 UTC, Benek6h commented on app/integration_test/navbar_test.dart
> +		);
This is good, but this doesn't test the navbar in the app environment.
The skeleton test that you had before was good. It iterated through all the pages that it should (dashboard, entries, settings, etc.).
To run it in the app environment, you need to import main as app and run it as app.main()

2023-11-05 01:22 UTC, S1robe requested changes
Great commits, but integration tests were not run, please run 'flutter test integration_test --branch' locally, which will create a different lcov.info file and then re commit so we can get an updated coverage metric.

Thank you!

2023-11-05 23:11 UTC, caelanot approved these changes
Thanks for adding the switch state to the push type for the navigation for different pages.

2023-11-06 02:50 UTC, S1robe approved these changes
Excellent PR, thank you for the contribution. Lets discuss sometime about adding custom animations to these transitions. 

Maybe if we did like a page turn or page flip animation like a book or notepad?

Thanks.

2023-11-06 03:48 UTC, S1robe approved these changes
Changes were made that resolve these requests. Resolving on Katrina's behalf.

2023-11-06 03:54 UTC, Benek6h approved these changes
Thank you for implementing my requested changes! Great job, looks amazing!

2023-11-06 03:56 UTC, merged