Added a save button to the user interface and a test for it.
S1robe/Pocket-Therapist pull request #72
Opened 2023-10-22 06:02 UTC by ian5924

# Description

This adds the save, plan, and tag buttons to the entries page. The buttons are non-functional.

Fixes # 4

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Test that all three buttons exist based on the key for each button. The test expects and finds a widget containing the text "Save", "Tag", and "Plan". 

**Test Configuration**:
* Firmware version: Android 12
* Hardware: Pixel 4
* Toolchain: Android API 31
* SDK: sdk_gphone64

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-22 21:59 UTC, Cooljawty requested changes
Looks like a good start, but it should be using the app theme and the tests need to be a bit more thorough.

2023-10-22 21:59 UTC, Cooljawty commented on app/test/save_journal_entry_button_test.dart
> +    await tester.pump();
You'll have to test the tap individualy.
so it would be tap() -> pump() -> make sure the right onTap method is called for each button

2023-10-22 21:59 UTC, Cooljawty commented on app/lib/pages/entries.dart
> +        color: Colors.grey,
The color should be defined by the app's theme. You can follow the guide from flutter: <https://docs.flutter.dev/cookbook/design/themes#apply-a-theme>

2023-10-25 06:23 UTC, ian5924 commented on app/test/save_journal_entry_button_test.dart
> +    await tester.pump();
Each button should have an individual test.
![image](https://github.com/S1robe/Pocket-Therapist/assets/103348036/7f8f635b-158c-411c-bd32-eff49db5d283)

2023-10-25 06:28 UTC, ian5924 commented on app/lib/pages/entries.dart
> +        color: Colors.grey,
The color is now defined by the app's theme.
![used theme](https://github.com/S1robe/Pocket-Therapist/assets/103348036/301aa77d-2c84-42c7-9dc2-283ef698ff60)

2023-10-26 01:18 UTC, Cooljawty approved these changes
Yep all the previous issues were addressed

2023-10-26 04:18 UTC, S1robe approved these changes
Looks good, lets merge this with the navigation bar.

Thanks for your contribution.

2023-10-26 04:19 UTC, merged