Added a button that takes the user to a page that will be able to add…
S1robe/Pocket-Therapist pull request #80
Opened 2023-10-30 22:23 UTC by caelanot

… a new entry.

Adds a button to the new entry page from entries.dart

# Description

User will be able to enter a journal entry on this page, which will be shown on the entries page for a specific day.

Fixes #22 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Testing widget existence
- [x] Testing text field inputs match expected results

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-10-30 23:03 UTC, caelanot commented
https://pub.dev/packages/syncfusion_flutter_gauges
https://pub.dev/packages/circular_seek_bar

Looking into these two packages for radial wheel for emotion input.
New entry button is on the entries.dart page (may be moved around later), saving functionality does not exist yet.

2023-11-01 00:32 UTC, Cooljawty requested changes
In summary:
 - save, plan, tag widget needs to be moved to the new_entry page
 - JournalEntry class needs to be implimented in the save gesture (I've defined the class in #60, so it can wait until thats been merged)
 - The button for new entries should be on the navigaton bar. Unless we've decided to change that from the prototype.

2023-11-01 00:32 UTC, Cooljawty commented on app/lib/pages/new_entry.dart
> +}
These functions should be handeled by the Bar from the entries page.
In fact I think we need to move it from the Entries page to this page.

2023-11-01 00:32 UTC, Cooljawty commented on app/lib/pages/entries.dart
> +    );
This button will be on the navigation bar.
I'd recommend waiting until the #68 is merged then adding the button to the navbar

2023-11-01 02:32 UTC, caelanot commented
> In summary:
> 
> * save, plan, tag widget needs to be moved to the new_entry page
> * JournalEntry class needs to be implimented in the save gesture (I've defined the class in [29 display card #60](https://github.com/S1robe/Pocket-Therapist/pull/60), so it can wait until thats been merged)
> * The button for new entries should be on the navigaton bar. Unless we've decided to change that from the prototype.

Okay that's what I figured was for the save/plan/ bar to be moved, I wasn't sure yet if the entries.dart page was for displaying entries or adding new ones, which was why I temporarily made the button its own thing and not yet in the bar.
Once #68 and #60 are handled I'll merge them over into this and move the new entry button as well.

2023-11-01 20:49 UTC, caelanot commented
@Cooljawty @S1robe Test nessage

2023-11-03 10:55 UTC, caelanot commented on app/lib/pages/new_entry.dart
> +}
Moved bar to new_entry page instead

2023-11-03 10:56 UTC, caelanot commented on app/lib/pages/entries.dart
> +    );
Temporary button on the page still, will change later

2023-11-04 15:37 UTC, Benek6h commented
You need to fix the merge conflicts before we review @caelanot

2023-11-05 07:09 UTC, ian5924 approved these changes
The button test are well done.
Thanks!

2023-11-05 18:52 UTC, S1robe requested changes
Code looks good, please run integration tests and commit your lcov.info file after running `flutter test integration_test --branch`

Thank you

2023-11-05 22:25 UTC, caelanot commented
> Code looks good, please run integration tests and commit your lcov.info file after running `flutter test integration_test --branch`
> 
> Thank you

Code coverage now updated with integration test results.

2023-11-05 22:36 UTC, S1robe reviewed
@caelanot Can you explain the difference between lib/pages/new_entry.dart and lib/pages/entry.dart 

Specifically the pages, it seems like there are two pages for the same thing.
Thank you for adding code coverage.

2023-11-05 22:58 UTC, caelanot commented
> @caelanot Can you explain the difference between lib/pages/new_entry.dart and lib/pages/entry.dart
> 
> Specifically the pages, it seems like there are two pages for the same thing. Thank you for adding code coverage.

The new_entry.dart page is what lets the user make a new journal entry, while entry.dart is for displaying an already created journal entry, which should be two separate pages.

2023-11-05 23:11 UTC, S1robe approved these changes
Looks good, thank you for the hard work!

I appreciate the concern for performance by creating two separate widgets rather than combining all the state into one.

Great job.

2023-11-05 23:14 UTC, merged